require("config.lazy")
require("config.theme")
require("config.keymap")
require("config.telescope")
require("config.treesitter")

vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
